<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="CraneSteering" Id="{11a0f5e4-dc13-4aac-aeaa-4d3c9914c435}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM CraneSteering
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

]]></ST>
    </Implementation>
    <LineIds Name="CraneSteering">
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>