<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{0ad4954e-ac64-46bb-9eb0-a0f0715ea3b1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Comment out as needed

HMISimulation();
//CraneSteering();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="2" />
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>