<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_HMISimulationJoystick" Id="{97020c3b-198f-42af-964f-b4237493cb4a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMISimulationJoystick
VAR_INPUT	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

// Signal to valve
HMIoutput.fHMIControlValveSignal := HMIinput.fHMIJoystick;]]></ST>
    </Implementation>
    <LineIds Name="FB_HMISimulationJoystick">
      <LineId Id="15" Count="2" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>