<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_ModeControlBox" Id="{5c8d61b7-c8a3-4bf0-98cd-78798a5dcb40}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ModeControlBox
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ModeControlBox">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>