<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_ManualControl" Id="{c3bab466-06a6-4c7e-b6e5-a4260602ff46}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ManualControl
VAR_INPUT
	bEnable : BOOL;
	eMode : E_Mode;
END_VAR
VAR_OUTPUT
	fManualControlOutput
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[


]]></ST>
    </Implementation>
    <LineIds Name="FB_ManualControl">
      <LineId Id="10" Count="0" />
      <LineId Id="16" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>